### ISSUE TITLE
Error on address (country) submission

### ISSUE THREAD

**Issue by cjweddell** [systopia/de.systopia.osm#15] opened 2020-07-17 08:59 UTC
I have an update your details profile which has started to throw a fatal error:

> Parse error: syntax error, unexpected 'new' (T_NEW) in /usr/local/php73/lib/php/HTTP/Request.php on line 412

When I remove the address fields it works as expected (I focused in on the address fields as it would save a phone number even when reporting the error).  On further testing it was including Country / County that triggered the error.

Through a process of elimination (enabling / disabling extensions) I have narrowed it down to OpenStreetMap Geocoding (de.systopia.osm).

I am using WordPress 5.4.2, CiviCRM 5.27.1, PHP Version 7.3.17.  The most significant change was recently upgraded to CiviCRM 5.27.1

**Comment by reswild** [comment] 2020-07-17 15:18
See the previous issue: https://github.com/bjendres/de.systopia.osm/issues/14

**Comment by bjendres** [comment] 2020-07-20 21:01
Thanks for reporting @cjweddell. As @reswild already indicated, this is most likely a duplicate of #14, so stay tuned.

**Closed as completed** 2020-12-08 12:32 UTC
Labels: bug
